# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # store test results
      - store_test_results:
          path: test_results

      # store code coverage
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

    steps:
      - attach_workspace:
        at: ~/repo
      - run:
        name: Authenticate with NPM
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
        name: Publish package
        command: npm publish --access public

workflows:
  # Name the workflow "welcome"
  version: 2
  build-and-publish:
    # Run the welcome/run job in its own container
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            -build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
